h1 header tag added
Ryan-Greenlee/Modern-Cloud pull request #2
Opened 2023-02-24 03:45 UTC by DestinySTLCC

2023-02-24 18:49 UTC, Ryan-Greenlee commented
Thank you for the pull request.

2023-02-24 18:51 UTC, Ryan-Greenlee reviewed
After this comment, I believe you can mark this as "Resolve Conversation"

2023-02-24 23:56 UTC, DestinySTLCC commented
Thank you, Ryan! I'll do that

2023-02-25 05:48 UTC, Ryan-Greenlee requested changes
OK to mark conversation as resolved

2023-02-25 05:54 UTC, Ryan-Greenlee approved these changes

2023-02-25 07:05 UTC, DestinySTLCC commented on index.html
> +<h1>
Is this the line I need to change?

2023-02-25 20:55 UTC, Ryan-Greenlee requested changes

2023-02-26 15:42 UTC, DestinySTLCC commented on index.html
> +<h1>
Thank you! I'll make a quick update.

2023-02-26 17:07 UTC, Ryan-Greenlee approved these changes

2023-02-26 17:19 UTC, merged